/*
 * This file is generated by jOOQ.
 */
package persistence.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Account(
    val id: UUID? = null, 
    val accountId: String? = null, 
    val createdBy: LocalDateTime? = null
): Serializable {

    override fun toString(): String {
        val sb = StringBuilder("Account (")

        sb.append(id)
        sb.append(", ").append(accountId)
        sb.append(", ").append(createdBy)

        sb.append(")")
        return sb.toString()
    }
}
