/*
 * This file is generated by jOOQ.
 */
package persistence.tables.references


import persistence.tables.Account
import persistence.tables.UserPrincipal



/**
 * The table <code>public.account</code>.
 */
val ACCOUNT = Account.ACCOUNT

/**
 * The table <code>public.user_principal</code>.
 */
val USER_PRINCIPAL = UserPrincipal.USER_PRINCIPAL
